---
# Override these in playbook with 'vars:' block

# Respond to ping requests
firewall_allow_ping: true

# Standard ports for web servers - 80 and 443
firewall_allow_web: true

# Enables SSH access
firewall_allow_ssh: true

# Allow connections on specified ports
# Ports without a protocol pair will be open for TCP and UDP traffic
# Examples: 53/udp, 80/tcp, 1194
firewall_open_ports: []

# TCP/UDP traffic originating from these IPs will be allowed explicitly
firewall_whitelisted_ips: []

# If that is not enough, you can supply your own iptables rules here
firewall_raw_rules: []
