---
# Configures a Metricbeat host

- name: Add HTTPS transport support to APT
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
  become: true

- name: Add Elasticsearch's official GPG key
  shell: curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
  become: true
  args:
    warn: False

- name: Add Elasticsearch's stable repository
  template: src=elasticsearch.list.j2 dest=/etc/apt/sources.list.d/elasticsearch.list
  become: true

- name: Install latest version of Metricbeat
  apt: name=metricbeat state=latest update_cache=yes
  become: true

- name: Copy configuration
  template:
    src: templates/metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  become: true

- name: Enable modules
  shell: metricbeat modules enable {{ item }}
  with_items: "{{ metricbeat_enabled_modules }}"
  become: true

- name: Start Metricbeat
  systemd: name=metricbeat enabled=yes state=restarted daemon_reload=true
  become: true
